In [2]:
import numpy as np
import pandas as pd
from tensorflow.keras.layers import *
import tensorflow.keras.backend as K
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sbn
import os
from functools import cmp_to_key
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.python.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import plot_model
from deepctr.inputs import SparseFeat, DenseFeat, VarLenSparseFeat, get_feature_names
from deepctr.models import DeepFM
import pickle
from tensorflow.keras import layers
import time
from tensorflow import feature_column
from tensorflow.keras.models import Model
from tensorflow.keras.utils import plot_model
import sys
%matplotlib inline

In [5]:
print(tf.constant(1.2))

tf.Tensor(1.2, shape=(), dtype=float32)


In [6]:
x = tf.constant([1,2.,3.3])

In [8]:
x.numpy()

array([1. , 2. , 3.3], dtype=float32)

In [9]:
a = tf.constant([[1,2],[3,4]])

In [10]:
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [11]:
tf.constant("hello")

<tf.Tensor: shape=(), dtype=string, numpy=b'hello'>

In [12]:
tf.constant(True)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [16]:
a = tf.constant(np.pi, dtype=tf.float64)

In [17]:
tf.cast(a, dtype=tf.int32)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [19]:
aa = tf.Variable(a)

In [20]:
aa.name

'Variable:0'

In [21]:
aa.trainable

True

In [22]:
tf.fill([], -1) # 标量

<tf.Tensor: shape=(), dtype=int32, numpy=-1>

In [23]:
tf.random.normal([2,2], mean=1,stddev=2)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 4.2086773 ,  0.60312265],
       [-0.91839385, -1.5920563 ]], dtype=float32)>

In [24]:
tf.range(10)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [25]:
# shape of tensor 't' is [2, 2, 3]
t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
tf.rank(t)  # 3

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [26]:
z = tf.random.normal([4,2])

In [31]:
b = tf.ones([2])

In [32]:
z

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[ 0.1219641 , -0.77068263],
       [ 1.1022455 ,  1.1368232 ],
       [ 0.904347  ,  2.5238264 ],
       [-0.43063203,  1.990701  ]], dtype=float32)>

In [33]:
b

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [34]:
z + b

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[1.1219641 , 0.22931737],
       [2.1022453 , 2.1368232 ],
       [1.904347  , 3.5238264 ],
       [0.569368  , 2.990701  ]], dtype=float32)>

In [35]:
fc = layers.Dense(3)

In [37]:
import tensorflow.keras as keras

In [41]:
(x_train,y_train),(x_test,y_test)=keras.datasets.imdb.load_data(num_words=10000)

In [45]:
x_train = keras.preprocessing.sequence.pad_sequences(x_train,maxlen=80)

In [49]:
x_train

array([[  15,  256,    4, ...,   19,  178,   32],
       [ 125,   68,    2, ...,   16,  145,   95],
       [ 645,  662,    8, ...,    7,  129,  113],
       ...,
       [ 529,  443,    2, ...,    4, 3586,    2],
       [ 286, 1814,   23, ...,   12,    9,   23],
       [  97,   90,   35, ...,  204,  131,    9]], dtype=int32)

In [51]:
x = tf.range(4)

In [52]:
x

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3], dtype=int32)>

In [58]:
# 第一层的参数
w1 = tf.Variable(tf.random.truncated_normal([784, 256], stddev=0.1))
b1 = tf.Variable(tf.zeros([256]))
# 第二层的参数
w2 = tf.Variable(tf.random.truncated_normal([256, 128], stddev=0.1))
b2 = tf.Variable(tf.zeros([128]))
# 第三层的参数
w3 = tf.Variable(tf.random.truncated_normal([128, 10], stddev=0.1))
b3 = tf.Variable(tf.zeros([10]))

In [59]:
print(x)

tf.Tensor([0 1 2 3], shape=(4,), dtype=int32)


In [60]:
a = tf.random.normal([4,3,28,32])

In [61]:
b = tf.random.normal([4,3,32,2])

In [66]:
# tf.matmul(a, b)

In [91]:
# concat 合并
a = tf.random.normal([10,35,4])
b = tf.random.normal([10,35,4])

In [74]:
tf.concat([a, b], axis=0).shape

TensorShape([20, 35, 4])

In [75]:
tf.concat([a, b], axis=1).shape

TensorShape([10, 70, 4])

In [90]:
#堆叠
tf.stack([a, b, a, b], axis=0).shape

TensorShape([4, 2, 3, 4])

In [85]:
a = tf.random.normal([2,3,4])
b = tf.random.normal([2,3,4])

In [88]:
tf.stack([a, b], axis=-1)

<tf.Tensor: shape=(2, 3, 4, 2), dtype=float32, numpy=
array([[[[ 2.2277613 ,  0.4359961 ],
         [-0.47428185, -1.2115512 ],
         [ 0.44591627, -0.38789627],
         [-0.9300328 ,  0.7079433 ]],

        [[ 0.8829968 , -0.4848898 ],
         [ 0.05749522,  0.7211726 ],
         [ 1.6011616 ,  0.6854169 ],
         [-1.4410216 , -0.4771604 ]],

        [[ 0.8077344 ,  1.0058799 ],
         [-0.04755918,  2.188618  ],
         [-0.29375467,  0.07006516],
         [ 0.62635463,  0.87957776]]],


       [[[-0.00895223, -0.18330534],
         [-0.02358091, -1.6866052 ],
         [ 0.66181034, -0.24705338],
         [-0.7274594 ,  0.54132473]],

        [[-1.4837512 , -0.08159825],
         [-0.21025321,  1.0224743 ],
         [-0.845249  , -0.0040364 ],
         [-0.9304    ,  1.3814347 ]],

        [[ 0.43983573, -1.2369268 ],
         [ 0.4619919 , -0.05443409],
         [-0.01372753,  0.6136587 ],
         [-0.54134923, -0.4020221 ]]]], dtype=float32)>

In [89]:
x = tf.random.normal([10,35,8])

In [103]:
# 分成多少分
len(tf.split(x, num_or_size_splits=4, axis=2))

4

In [110]:
tf.split(x, num_or_size_splits=8, axis=2)[0].shape

TensorShape([10, 35, 1])

In [116]:
#求范数
# 向量范数
x = tf.ones([2,2])
# l1 ‖𝒙‖1 = ∑|𝑥𝑖|
print(tf.norm(x,ord=1))
#l2 ‖𝒙‖2 = √∑|𝑥𝑖|2
print(tf.norm(x,ord=2))
print(tf.norm(x,ord=3))
#无穷范数 ‖𝒙‖∞ = 𝑚𝑎𝑥𝑖(|Xi|）
print(tf.norm(x,ord=np.inf))

tf.Tensor(4.0, shape=(), dtype=float32)
tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(1.587401, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)


In [124]:
#最大、最小、均值
x = tf.random.normal([4,3, 2])
print(x)

tf.Tensor(
[[[-0.7731563  -1.0289005 ]
  [ 1.8121519  -2.770237  ]
  [-0.7411836   0.8069693 ]]

 [[-0.8877237  -1.6526408 ]
  [-1.2580543   0.03503527]
  [ 1.0247425  -0.13461505]]

 [[ 0.9788749   0.01326492]
  [-1.3666195  -0.6058809 ]
  [ 0.31650978 -1.4371299 ]]

 [[ 0.7690191   0.74325866]
  [ 0.4926077   0.96697366]
  [ 0.95644146 -1.2958633 ]]], shape=(4, 3, 2), dtype=float32)


In [125]:
tf.reduce_max(x,axis=0)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.9788749 , 0.74325866],
       [1.8121519 , 0.96697366],
       [1.0247425 , 0.8069693 ]], dtype=float32)>

In [126]:
tf.reduce_max(x,axis=1)

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[1.8121519 , 0.8069693 ],
       [1.0247425 , 0.03503527],
       [0.9788749 , 0.01326492],
       [0.95644146, 0.96697366]], dtype=float32)>

In [127]:
tf.reduce_max(x,axis=2)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[-0.7731563 ,  1.8121519 ,  0.8069693 ],
       [-0.8877237 ,  0.03503527,  1.0247425 ],
       [ 0.9788749 , -0.6058809 ,  0.31650978],
       [ 0.7690191 ,  0.96697366,  0.95644146]], dtype=float32)>

In [129]:
#计算梯度
import tensorflow as tf
x= tf.Variable(initial_value=3.0)
with tf.GradientTape(persistent=True) as g:
    y = x * x
dy_dx = g.gradient(y, x)  # Will compute to 6.0
print(dy_dx)
dy_dx = g.gradient(y, x)
print(dy_dx)


tf.Tensor(6.0, shape=(), dtype=float32)
tf.Tensor(6.0, shape=(), dtype=float32)


In [130]:
dy_dx = g.gradient(y, x)  # Will compute to 6.0
print(dy_dx)
dy_dx = g.gradient(y, x)
print(dy_dx)


tf.Tensor(6.0, shape=(), dtype=float32)
tf.Tensor(6.0, shape=(), dtype=float32)


In [133]:
#张量实现方式
x = tf.random.normal([2,784])
w1 = tf.Variable(tf.random.truncated_normal([784, 256], stddev=0.1))
b1 = tf.Variable(tf.zeros([256]))
o1 = tf.matmul(x,w1) + b1 # 线性变换
o1 = tf.nn.relu(o1) # 激活函数
print(o1.shape)

(2, 256)


In [138]:
fc = layers.Dense(256, activation=tf.nn.relu) 
h1 = fc(x)

In [139]:
fc.kernel

<tf.Variable 'dense_3/kernel:0' shape=(784, 256) dtype=float32, numpy=
array([[-0.06229118,  0.05943532,  0.0146779 , ...,  0.02113614,
        -0.00942149,  0.05618919],
       [-0.02688813, -0.02853279,  0.00678993, ...,  0.01518399,
        -0.03677334, -0.04294223],
       [-0.00913209,  0.01346541,  0.06296282, ...,  0.01431133,
        -0.03106543,  0.0378487 ],
       ...,
       [-0.02109246,  0.04593825,  0.04364695, ...,  0.02993513,
         0.03126418, -0.00694859],
       [-0.00938377, -0.00382872,  0.03139634, ...,  0.05739358,
         0.05555041,  0.05236149],
       [-0.02201288, -0.04437279, -0.05767102, ..., -0.00504839,
        -0.03712071,  0.04940148]], dtype=float32)>

In [143]:
fc.weights

[<tf.Variable 'dense_3/kernel:0' shape=(784, 256) dtype=float32, numpy=
 array([[-0.06229118,  0.05943532,  0.0146779 , ...,  0.02113614,
         -0.00942149,  0.05618919],
        [-0.02688813, -0.02853279,  0.00678993, ...,  0.01518399,
         -0.03677334, -0.04294223],
        [-0.00913209,  0.01346541,  0.06296282, ...,  0.01431133,
         -0.03106543,  0.0378487 ],
        ...,
        [-0.02109246,  0.04593825,  0.04364695, ...,  0.02993513,
          0.03126418, -0.00694859],
        [-0.00938377, -0.00382872,  0.03139634, ...,  0.05739358,
          0.05555041,  0.05236149],
        [-0.02201288, -0.04437279, -0.05767102, ..., -0.00504839,
         -0.03712071,  0.04940148]], dtype=float32)>,
 <tf.Variable 'dense_3/bias:0' shape=(256,) dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [141]:
fc.bias

<tf.Variable 'dense_3/bias:0' shape=(256,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 

In [144]:
fc.variables

[<tf.Variable 'dense_3/kernel:0' shape=(784, 256) dtype=float32, numpy=
 array([[-0.06229118,  0.05943532,  0.0146779 , ...,  0.02113614,
         -0.00942149,  0.05618919],
        [-0.02688813, -0.02853279,  0.00678993, ...,  0.01518399,
         -0.03677334, -0.04294223],
        [-0.00913209,  0.01346541,  0.06296282, ...,  0.01431133,
         -0.03106543,  0.0378487 ],
        ...,
        [-0.02109246,  0.04593825,  0.04364695, ...,  0.02993513,
          0.03126418, -0.00694859],
        [-0.00938377, -0.00382872,  0.03139634, ...,  0.05739358,
          0.05555041,  0.05236149],
        [-0.02201288, -0.04437279, -0.05767102, ..., -0.00504839,
         -0.03712071,  0.04940148]], dtype=float32)>,
 <tf.Variable 'dense_3/bias:0' shape=(256,) dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [142]:
fc.trainable_variables

[<tf.Variable 'dense_3/kernel:0' shape=(784, 256) dtype=float32, numpy=
 array([[-0.06229118,  0.05943532,  0.0146779 , ...,  0.02113614,
         -0.00942149,  0.05618919],
        [-0.02688813, -0.02853279,  0.00678993, ...,  0.01518399,
         -0.03677334, -0.04294223],
        [-0.00913209,  0.01346541,  0.06296282, ...,  0.01431133,
         -0.03106543,  0.0378487 ],
        ...,
        [-0.02109246,  0.04593825,  0.04364695, ...,  0.02993513,
          0.03126418, -0.00694859],
        [-0.00938377, -0.00382872,  0.03139634, ...,  0.05739358,
          0.05555041,  0.05236149],
        [-0.02201288, -0.04437279, -0.05767102, ..., -0.00504839,
         -0.03712071,  0.04940148]], dtype=float32)>,
 <tf.Variable 'dense_3/bias:0' shape=(256,) dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [146]:
x = tf.linspace(-6.,6.,10)

In [148]:
tf.nn.sigmoid(x)

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.00247262, 0.00931596, 0.0344452 , 0.11920292, 0.33924368,
       0.6607564 , 0.880797  , 0.96555483, 0.99068403, 0.9975274 ],
      dtype=float32)>

In [149]:
x

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-6.       , -4.6666665, -3.3333333, -2.       , -0.6666665,
        0.666667 ,  2.       ,  3.333334 ,  4.666667 ,  6.       ],
      dtype=float32)>

#### sigmoid 优缺点
优点

是能够把𝑥 ∈ 𝑅的输入“压缩”到𝑥 ∈ (0,1)区间，这个区间的数值在机器学习常用来表示

❑ 概率分布 (0,1)区间的输出和概率的分布范围[0,1]契合，可以通过 Sigmoid 函数将输出
转译为概率输出


❑ 信号强度 一般可以将 0~1 理解为某种信号的强度，如像素的颜色强度，1 代表当前通
道颜色最强，0 代表当前通道无颜色；抑或代表门控值(Gate)的强度，1 代表当前门控
全部开放，0代表当前门口关闭

缺点 

但是 Sigmoid 函数在输入值较大或较小时容易出现梯度值接近于 0 的现象，称为梯度弥散现象。出现梯度弥散现象时，网络参数长时间得不到更新，
导致训练不收敛或停滞不动的现象发生，较深层次的网络模型中更容易出现梯度弥散现象。

#### ReLU 
优点

它具有单侧抑制、相对宽松的兴奋边界等特性

#### LeakReLU

#### Tanh
tanh(𝑥) = (e𝑥 − e−𝑥) (e𝑥 + e−𝑥) = 2 ∙ sigmoid(2𝑥) − 1

In [152]:
z = tf.constant([2.,1.,0.1])

In [153]:
tf.nn.softmax(z)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.6590012, 0.242433 , 0.0985659], dtype=float32)>

In [156]:
z = tf.random.normal([2,10]) # 构造输出层的输出
y_onehot = tf.constant([1,3]) # 构造真实值
y_onehot = tf.one_hot(y_onehot, depth=10) # one-hot 编码
# 输出层未使用 Softmax 函数，故 from_logits 设置为 True
# 这样 categorical_crossentropy 函数在计算损失函数前，会先内部调用 Softmax 函数
print(z)
print(y_onehot)

tf.Tensor(
[[ 0.76961786 -1.5097655   0.6088267   0.80532235  1.4010354   0.5013814
   1.8998561  -0.6220406  -0.24049367  0.11527412]
 [ 2.4950454   0.44667011  1.7740879   1.3869336   0.46174526 -0.59181076
   0.24524622 -2.2908068   1.6629468  -0.36382884]], shape=(2, 10), dtype=float32)
tf.Tensor(
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]], shape=(2, 10), dtype=float32)


In [159]:
loss = keras.losses.categorical_crossentropy(y_onehot,z,from_logits=True)
print(loss)

tf.Tensor([4.568294  2.1117525], shape=(2,), dtype=float32)


In [158]:
loss = tf.reduce_mean(loss) # 计算平均交叉熵损失
print(loss)

tf.Tensor(3.3400233, shape=(), dtype=float32)


In [161]:
dataset_path = keras.utils.get_file("auto-mpg.data",  "http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data")

32768/30286 [================================] - 1s 25us/step


In [162]:
column_names = ['MPG','Cylinders','Displacement','Horsepower','Weight',
'Acceleration', 'Model Year', 'Origin']
raw_dataset = pd.read_csv(dataset_path, names=column_names,
na_values = "?", comment='\t',
sep=" ", skipinitialspace=True)
dataset = raw_dataset.copy()

In [163]:
dataset.head()

MPG  Cylinders  Displacement  Horsepower  Weight  Acceleration  \
0  18.0          8         307.0       130.0  3504.0          12.0   
1  15.0          8         350.0       165.0  3693.0          11.5   
2  18.0          8         318.0       150.0  3436.0          11.0   
3  16.0          8         304.0       150.0  3433.0          12.0   
4  17.0          8         302.0       140.0  3449.0          10.5   

   Model Year  Origin  
0          70       1  
1          70       1  
2          70       1  
3          70       1  
4          70       1

In [166]:
dataset.isna().sum()

MPG             0
Cylinders       0
Displacement    0
Horsepower      6
Weight          0
Acceleration    0
Model Year      0
Origin          0
dtype: int64

In [167]:
dataset = dataset.dropna()

In [168]:
dataset.isna().sum()

MPG             0
Cylinders       0
Displacement    0
Horsepower      0
Weight          0
Acceleration    0
Model Year      0
Origin          0
dtype: int64

In [169]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 392 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   MPG           392 non-null    float64
 1   Cylinders     392 non-null    int64  
 2   Displacement  392 non-null    float64
 3   Horsepower    392 non-null    float64
 4   Weight        392 non-null    float64
 5   Acceleration  392 non-null    float64
 6   Model Year    392 non-null    int64  
 7   Origin        392 non-null    int64  
dtypes: float64(5), int64(3)
memory usage: 27.6 KB


In [171]:
origin = dataset.pop('Origin')

In [172]:
dataset['USA'] = (origin == 1)*1.0
dataset['Europe'] = (origin == 2)*1.0
dataset['Japan'] = (origin == 3)*1.0
dataset.tail() 

MPG  Cylinders  Displacement  Horsepower  Weight  Acceleration  \
393  27.0          4         140.0        86.0  2790.0          15.6   
394  44.0          4          97.0        52.0  2130.0          24.6   
395  32.0          4         135.0        84.0  2295.0          11.6   
396  28.0          4         120.0        79.0  2625.0          18.6   
397  31.0          4         119.0        82.0  2720.0          19.4   

     Model Year  USA  Europe  Japan  
393          82  1.0     0.0    0.0  
394          82  0.0     1.0    0.0  
395          82  1.0     0.0    0.0  
396          82  1.0     0.0    0.0  
397          82  1.0     0.0    0.0

In [177]:
train_dataset = dataset.sample(frac=0.8,random_state=0)
test_dataset = dataset.drop(train_dataset.index)

In [178]:
train_labels = train_dataset.pop('MPG')
test_labels = test_dataset.pop('MPG')

In [179]:
train_stats = train_dataset.describe()
train_stats = train_stats.transpose() # 转置

In [180]:
train_stats.info

<bound method DataFrame.info of               count         mean         std     min      25%     50%  \
Cylinders     314.0     5.477707    1.699788     3.0     4.00     4.0   
Displacement  314.0   195.318471  104.331589    68.0   105.50   151.0   
Horsepower    314.0   104.869427   38.096214    46.0    76.25    94.5   
Weight        314.0  2990.251592  843.898596  1649.0  2256.50  2822.5   
Acceleration  314.0    15.559236    2.789230     8.0    13.80    15.5   
Model Year    314.0    75.898089    3.675642    70.0    73.00    76.0   
USA           314.0     0.624204    0.485101     0.0     0.00     1.0   
Europe        314.0     0.178344    0.383413     0.0     0.00     0.0   
Japan         314.0     0.197452    0.398712     0.0     0.00     0.0   

                  75%     max  
Cylinders        8.00     8.0  
Displacement   265.75   455.0  
Horsepower     128.00   225.0  
Weight        3608.00  5140.0  
Acceleration    17.20    24.8  
Model Year      79.00    82.0  
USA          

In [181]:
# 标准化数据
def norm(x): # 减去每个字段的均值，并除以标准差
    return (x - train_stats['mean']) / train_stats['std']
normed_train_data = norm(train_dataset) # 标准化训练集
normed_test_data = norm(test_dataset) # 标准化测试集

In [182]:
print(normed_train_data.shape,train_labels.shape)
print(normed_test_data.shape, test_labels.shape)

(314, 9) (314,)
(78, 9) (78,)


In [183]:
train_db = tf.data.Dataset.from_tensor_slices((normed_train_data.values, 
train_labels.values)) # 构建 Dataset 对象
train_db = train_db.shuffle(100).batch(32) # 随机打散，批量化

In [190]:
class Network(keras.Model):
    def __init__(self):
        super(Network, self).__init__()
        # 创建 3 个全连接层
        self.fc1 = layers.Dense(64, activation='relu')
        self.fc2 = layers.Dense(32, activation='relu')
        self.fc3 = layers.Dense(16, activation='relu')
        self.fc4 = layers.Dense(1, activation='relu')
    def call(self, inputs, training=None, mask=None):
        # 依次通过 3 个全连接层
        x = self.fc1(inputs)
        x = self.fc2(x)
        x = self.fc3(x)
        x = self.fc4(x)
        return x

In [191]:
model = Network() # 创建网络类实例
# 通过 build 函数完成内部张量的创建，其中 4 为任意设置的 batch 数量，9 为输入特征长度
model.build(input_shape=(4, 9))
model.summary() # 打印网络信息
optimizer = tf.keras.optimizers.RMSprop(0.001) # 创建优化器，指定学习率

Model: "network_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_12 (Dense)             multiple                  640       
_________________________________________________________________
dense_13 (Dense)             multiple                  2080      
_________________________________________________________________
dense_14 (Dense)             multiple                  528       
_________________________________________________________________
dense_15 (Dense)             multiple                  17        
Total params: 3,265
Trainable params: 3,265
Non-trainable params: 0
_________________________________________________________________


In [196]:
for epoch in range(200):
    for step, (x, y) in enumerate(train_db):
        with tf.GradientTape() as tape:
            out = model(x)
            loss = tf.reduce_mean(keras.losses.MSE(y, out))
            mae_loss = tf.reduce_mean(keras.losses.MAE(y, out))
        if step % 10 == 0: # 间隔性地打印训练误差
            print(epoch, step, float(loss))
        # 计算梯度，并更新
        grads = tape.gradient(loss, model.trainable_variables)
        optimizer.apply_gradients(zip(grads, model.trainable_variables))

0 0 617.6878051757812
1 0 560.48828125
2 0 600.5587158203125
3 0 463.64599609375
4 0 413.1461181640625
5 0 229.5828094482422
6 0 200.75350952148438
7 0 183.30506896972656
8 0 173.47332763671875
9 0 129.59918212890625
10 0 78.73400115966797
11 0 82.20797729492188
12 0 97.92155456542969
13 0 52.692230224609375
14 0 65.36075592041016
15 0 54.0609130859375
16 0 48.34896469116211
17 0 53.41855239868164
18 0 96.69974517822266
19 0 64.48368835449219
20 0 78.51432800292969
21 0 60.2833251953125
22 0 68.36736297607422
23 0 79.81006622314453
24 0 66.8126220703125
25 0 64.64549255371094
26 0 68.41786193847656
27 0 75.76280212402344
28 0 74.2781982421875
29 0 89.53421020507812
30 0 58.678138732910156
31 0 67.06952667236328
32 0 73.95379638671875
33 0 59.27793884277344
34 0 47.32247543334961
35 0 64.2625961303711
36 0 48.946353912353516
37 0 69.34854125976562
38 0 60.33689498901367
39 0 69.88017272949219
40 0 67.77163696289062
41 0 85.75296783447266
42 0 66.87680053710938
43 0 38.77245330810547
44 

In [197]:
y_true = [[0, 1], [0, 0]]
y_pred = [[0.6, 0.4], [0.4, 0.6]]
loss = tf.keras.losses.binary_crossentropy(y_true, y_pred)
assert loss.shape == (2,)
loss.numpy()

array([0.9162905 , 0.71355796], dtype=float32)